### ISSUE TITLE
Does Kafka Monitor support Kerberos Cluster

### ISSUE THREAD

**Issue by rajeshhdp** [linkedin/kafka-monitor#105]
I am trying to make it work with Kerberoised cluster but seeing below error, Does this support kerberos ?
] ERROR single-cluster-monitor/MultiClusterTopicManagementService will stop due to error. (com.linkedin.kmf.services.MultiClusterTopicManagementService)
kafka.common.KafkaException: Failed to parse the broker info from zookeeper: {"jmx_port":-1,"timestamp":"1513377854404","endpoints":["PLAINTEXTSASL://new-server.abc.net:6667"],"host":null,"version":3,"port":-1}
        at kafka.cluster.Broker$.createBroker(Broker.scala:125)
        at kafka.utils.ZkUtils.getBrokerInfo(ZkUtils.scala:843)
        at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:286)
        at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:286)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at kafka.utils.ZkUtils.getAllBrokersInCluster(ZkUtils.scala:286)
        at com.linkedin.kmf.common.Utils.createMonitoringTopicIfNotExists(Utils.java:92)
        at com.linkedin.kmf.topicfactory.DefaultTopicFactory.createTopicIfNotExist(DefaultTopicFactory.java:26)
        at com.linkedin.kmf.services.MultiClusterTopicManagementService$TopicManagementHelper.maybeCreateTopic(MultiClusterTopicManagementService.java:211)
        at com.linkedin.kmf.services.MultiClusterTopicManagementService$TopicManagementRunnable.run(MultiClusterTopicManagementService.java:143)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener PLAINTEXTSASL
        at kafka.cluster.EndPoint$$anonfun$securityProtocol$1$1.apply(EndPoint.scala:48)
        at kafka.cluster.EndPoint$$anonfun$securityProtocol$1$1.apply(EndPoint.scala:48)
        at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
        at scala.collection.AbstractMap.getOrElse(Map.scala:59)
        at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:47)
        at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:56)
        at kafka.cluster.Broker$$anonfun$2.apply(Broker.scala:115)
        at kafka.cluster.Broker$$anonfun$2.apply(Broker.scala:115)
        at scala.collection.immutable.List.map(List.scala:273)
        at kafka.cluster.Broker$.createBroker(Broker.scala:115)
        ... 21 more

**Comment by lindong28** [comment]
@rajeshhdp we have not tested the whether Kafka Monitor support Kerberos Cluster. But this error does not seem to be related to the use of Kerberos.

Can you tell me the githash of the Kafka Monitor and the version of the Kafka cluster in this deployment? Thanks.

**Comment by rajeshhdp** [comment]
@lindong28 thanks for the quick response , here is the info 
githash : 6722470d21174ee62bea1cda81dfb0a52ed40697
Kafka Version : 0.10.0.2.5
Thanks.

**Comment by lindong28** [comment]
@rajeshhdp Hmm... there is no Kafka version 0.10.0.2.5. Can you double check?

**Comment by hackerwin7** [comment]
It should be `SASL_PLAINTEXT` not `PLAINTEXTSASL`
