### ISSUE TITLE
Java Error fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF

### ISSUE THREAD

**Issue by michalss** [linkedin/kafka-monitor#137]
Hi, can anyone please help solve this issue for me pls ?

Exception in thread "main" com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (String)"{  "single-cluster-monitor": {    "class.name": "com.linkedin.kmf.apps.SingleClusterMonitor",    "topic": "kafka-monitor-topic",    "zookeeper.connect": "zoo1:2181,zoo2:2181,zoo3:2181",    "bootstrap.servers": "kafka1:9092,kafka2:9092,kafka3:9092",    "produce.record.delay.ms": 100,    "topic-management.topicCreationEnabled": true,    "topic-management.replicationFactor" : 1,    "topic-management.partitionsToBrokersRatio" : 2.0,    "topic-management.reba"[truncated 1418 chars]; line: 1, column: 1])
 at [Source: (String)"{  "single-cluster-monitor": {    "class.name": "com.linkedin.kmf.apps.SingleClusterMonitor",    "topic": "kafka-monitor-topic",    "zookeeper.connect": "10.10.180.81:2181,10.10.180.82:2181,10.10.180.83:2181",    "bootstrap.servers": "10.10.180.84:9092,10.10.180.85:9092,10.10.180.86:9092",    "produce.record.delay.ms": 100,    "topic-management.topicCreationEnabled": true,    "topic-management.replicationFactor" : 1,    "topic-management.partitionsToBrokersRatio" : 2.0,    "topic-management.reba"[truncated 1418 chars]; line: 1, column: 3837]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:594)
        at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:485)
        at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:497)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2332)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:880)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:512)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at com.linkedin.kmf.KafkaMonitor.main(KafkaMonitor.java:174)

**Comment by lindong28** [comment]
@michalss It seems that the config file provided to KafkaMonitor can not be passed. Can you provide the config file so that the issue can be reproduced?
