### ISSUE TITLE
Error This server does not host this topic-partition.

### ISSUE THREAD

**Issue by quangvuptit** [linkedin/kafka-monitor#184]
```
[2019-12-17 09:57:03,588] INFO single-cluster-monitor/ProduceService is initialized. (com.linkedin.kmf.services.ProduceService)
[2019-12-17 09:57:03,616] INFO ConsumeServiceConfig values: 
	bootstrap.servers = 10.10.12.94:9092
	consume.consumer.class = com.linkedin.kmf.consumer.NewConsumer
	consume.latency.percentile.granularity.ms = 1
	consume.latency.percentile.max.ms = 5000
	consume.latency.sla.ms = 20000
	topic = kafka-monitor-topic
	zookeeper.connect = 10.10.12.94:2181
 (com.linkedin.kmf.services.configs.ConsumeServiceConfig)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.linkedin.kmf.KafkaMonitor.<init>(KafkaMonitor.java:68)
	at com.linkedin.kmf.KafkaMonitor.main(KafkaMonitor.java:166)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at com.linkedin.kmf.services.ConsumeService$ConsumeMetrics.<init>(ConsumeService.java:228)
	at com.linkedin.kmf.services.ConsumeService.<init>(ConsumeService.java:126)
	at com.linkedin.kmf.apps.SingleClusterMonitor.<init>(SingleClusterMonitor.java:56)
	... 6 more
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
```

**Comment by andrewchoi5** [comment]
Hi Quangvuptit, we have a open PR for this and will be merged as soon as it is reviewed.

**Comment by andrewchoi5** [comment]
`https://github.com/linkedin/kafka-monitor/pull/181 `
cc: @smccauliff
