### ISSUE TITLE
Error using KafkaMetricsReporter

### ISSUE THREAD

**Issue by joshuaspaulding** [linkedin/kafka-monitor#235]
I am receiving an error when attempting to use the KafkaMetricsReporter service.

This is the exception on startup:
```bash
Exception in thread "main" java.lang.NoSuchMethodException: com.linkedin.kmf.services.KafkaMetricsReporterService.<init>(java.util.Map, java.lang.String)
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at com.linkedin.kmf.KafkaMonitor.<init>(KafkaMonitor.java:84)
	at com.linkedin.kmf.KafkaMonitor.main(KafkaMonitor.java:188)
```

Attached is my properties file:
```json
{
    "produce-service": {
        "class.name": "com.linkedin.kmf.services.ProduceService",
        "topic": "kafka-monitor-topic",
        "zookeeper.connect": "localhost:2181",
        "bootstrap.servers": "localhost:9092",
        "consume.latency.sla.ms": "20000",
        "consume.consumer.props": {}
    },

    "consume-service": {
        "class.name": "com.linkedin.kmf.services.ConsumeService",
        "topic": "kafka-monitor-topic",
        "zookeeper.connect": "localhost:2181",
        "bootstrap.servers": "localhost:9092",
        "consume.latency.sla.ms": "20000",
        "consume.consumer.props": {}
    },

    "reporter-kafka-service": {
        "class.name": "com.linkedin.kmf.services.KafkaMetricsReporterService",
        "report.interval.sec": 3,
        "zookeeper.connect": "localhost:2181",
        "bootstrap.servers": "localhost:9092",
        "topic": "kafka-monitor-topic-metrics",
        "report.kafka.topic.replication.factor": 1,
        "report.metrics.list": [
          "kmf.services:type=produce-service,name=*:produce-availability-avg",
          "kmf.services:type=consume-service,name=*:consume-availability-avg",
          "kmf.services:type=produce-service,name=*:records-produced-total",
          "kmf.services:type=consume-service,name=*:records-consumed-total",
          "kmf.services:type=consume-service,name=*:records-lost-total",
          "kmf.services:type=consume-service,name=*:records-duplicated-total",
          "kmf.services:type=consume-service,name=*:records-delay-ms-avg",
          "kmf.services:type=produce-service,name=*:records-produced-rate",
          "kmf.services:type=produce-service,name=*:produce-error-rate",
          "kmf.services:type=consume-service,name=*:consume-error-rate"
        ]
    }
}
```

It appears this [commit](https://github.com/linkedin/kafka-monitor/commit/fd12d19323d29015d103cf98b4763356f7428503#diff-18c065366c6b38fda930376886220e96R43) modified the method signature of the KafkaMetricReporter service, thus causing it to fail.

**Comment by andrewchoi5** [comment]
Hello Joshua, please refer to the excerpt from my log. Also, your PR's CI travis build is currently failing. please check.

The HEAD of the master branch seems to be working fine on my end. Have you tried running 

`./gradlew clean build && ./gradlew jar && ./bin/kafka-monitor-start.sh config/kafka-monitor.properties`

with (of course) at least on kafka server and zookeeper server running?

```[2020-04-09 15:44:17,184] INFO ==============================================================
kmf:type=kafka-monitor:offline-runnable-count=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:produce-availability-avg=1.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-availability-avg=1.0
kmf.services:name=single-cluster-monitor,type=commit-availability-service:offsets-committed-avg=1.0
kmf.services:name=single-cluster-monitor,type=commit-availability-service:failed-commit-offsets-avg=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-total=776.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-consumed-total=754.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-duplicated-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-delay-ms-avg=3.282493368700265
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-rate=12.970949085681811
kmf.services:name=single-cluster-monitor,type=produce-service:produce-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=commit-availability-service:offsets-committed-total=10.0
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-avg=2.7
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-max=11.0
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-99th=10.995601759296282
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-999th=10.995601759296282
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-9999th=10.995601759296282
kmf.services:name=single-cluster-monitor,type=commit-availability-service:failed-commit-offsets-total=0.0
 (com.linkedin.kmf.services.DefaultMetricsReporterService)
[2020-04-09 15:44:18,184] INFO ==============================================================
kmf:type=kafka-monitor:offline-runnable-count=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:produce-availability-avg=1.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-availability-avg=1.0
kmf.services:name=single-cluster-monitor,type=commit-availability-service:offsets-committed-avg=1.0
kmf.services:name=single-cluster-monitor,type=commit-availability-service:failed-commit-offsets-avg=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-total=794.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-consumed-total=772.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-duplicated-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-delay-ms-avg=3.2629533678756477
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-rate=13.272265311580638
kmf.services:name=single-cluster-monitor,type=produce-service:produce-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=commit-availability-service:offsets-committed-total=11.0
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-avg=2.6363636363636362
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-max=11.0
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-99th=10.995601759296282
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-999th=10.995601759296282
kmf.services:name=single-cluster-monitor,type=commit-latency-service:commit-offset-latency-ms-9999th=10.995601759296282
kmf.services:name=single-cluster-monitor,type=commit-availability-service:failed-commit-offsets-total=0.0
 (com.linkedin.kmf.services.DefaultMetricsReporterService)```

**Comment by joshuaspaulding** [comment]
Your log appears to be the DefaultMetricsReporterService which does work as expected.  My issue is with the KafkaMetricsReporterService; class.name: com.linkedin.kmf.services.KafkaMetricsReporterService.  I'll check the CI travis build.
