### ISSUE TITLE
 Metadata update failed & Exception occurred while retrieving the topic description

### ISSUE THREAD

**Issue by snmsmanager** [linkedin/kafka-monitor#240]
Hi ,

I'm going to monitor SASL enaabled Kafka cluster using kafka-monitor and I've recived below error while running .

**2020-04-14 13:11:21 ERROR ConsumeMetrics:61 - Exception occurred while retrieving the topic description.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[kafka-clients-2.4.0.jar:?]
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) ~[kafka-clients-2.4.0.jar:?]
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) ~[kafka-clients-2.4.0.jar:?]
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) ~[kafka-clients-2.4.0.jar:?]
        at com.linkedin.kmf.services.ConsumeMetrics.lambda$new$0(ConsumeMetrics.java:59) ~[kafka-monitor-2.0.10-SNAPSHOT.jar:2.0.10-SNAPSHOT]
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_211]
        at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:717) ~[?:1.8.0_211]
        at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2010) ~[?:1.8.0_211]
        at com.linkedin.kmf.services.ConsumeMetrics.<init>(ConsumeMetrics.java:53) ~[kafka-monitor-2.0.10-SNAPSHOT.jar:2.0.10-SNAPSHOT]
        at com.linkedin.kmf.services.ConsumeService.lambda$new$1(ConsumeService.java:71) ~[kafka-monitor-2.0.10-SNAPSHOT.jar:2.0.10-SNAPSHOT]
        at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) [?:1.8.0_211]
        at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:717) [?:1.8.0_211]
        at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2010) [?:1.8.0_211]
        at com.linkedin.kmf.services.ConsumeService.<init>(ConsumeService.java:63) [kafka-monitor-2.0.10-SNAPSHOT.jar:2.0.10-SNAPSHOT]
        at com.linkedin.kmf.apps.SingleClusterMonitor.<init>(SingleClusterMonitor.java:63) [kafka-monitor-2.0.10-SNAPSHOT.jar:2.0.10-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_211]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_211]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_211]
        at com.linkedin.kmf.KafkaMonitor.<init>(KafkaMonitor.java:71) [kafka-monitor-2.0.10-SNAPSHOT.jar:2.0.10-SNAPSHOT]
        at com.linkedin.kmf.KafkaMonitor.main(KafkaMonitor.java:188) [kafka-monitor-2.0.10-SNAPSHOT.jar:2.0.10-SNAPSHOT]
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.**

Also all metrics are zero..
**kmf:type=kafka-monitor:offline-runnable-count=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:produce-availability-avg=NaN
kmf.services:name=single-cluster-monitor,type=consume-service:consume-availability-avg=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-consumed-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-duplicated-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-delay-ms-avg=NaN
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-rate=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:produce-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-error-rate=0.0**

ssl.properties
"single-cluster-monitor": {
    "class.name": "com.linkedin.kmf.apps.SingleClusterMonitor",
    "topic": "billpayment",
    "zookeeper.connect": "192.168.8.100:2181",
    "bootstrap.servers": "192.168.8.100:9093",
    "request.timeout.ms": 9000,
    "produce.record.delay.ms": 100,
    "topic-management.topicCreationEnabled": false,
    "topic-management.replicationFactor" : 1,
    "topic-management.partitionsToBrokersRatio" : 2.0,
    "topic-management.rebalance.interval.ms" : 600000,
    "topic-management.preferred.leader.election.check.interval.ms" : 300000,
    "topic-management.topicFactory.props": {
    },
    "topic-management.topic.props": {
      "retention.ms": "3600000"
    },
    "produce.producer.props": {
      "client.id": "kmf-client-id",
      "producer.security.protocol": "SASL_SSL",
      "sasl.mechanism": "GSSAPI",
      "sasl.kerberos.service.name": "kafka",
      "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"testadmin\" password=\"TestSG9GVgE@#\";",
      "producer.ssl.truststore.location": "/opt/kafka-monitor/keys/kafka.truststore.jks",
      "producer.ssl.truststore.password": "changeit",
      "producer.ssl.keystore.location": "/opt/kafka-monitor/keys/kafka.keystore.jks",
      "producer.ssl.keystore.password": "changeit"
    },

    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {
      "consumer.security.protocol": "SASL_SSL",
      "sasl.mechanism": "GSSAPI",
      "sasl.kerberos.service.name": "kafka",
      "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"testadmin\" password=\"TestSG9GVgE@#\";",
      "consumer.ssl.truststore.location": "/opt/kafka-monitor/keys/kafka.truststore.jks",
      "consumer.ssl.truststore.password": "changeit",
      "consumer.ssl.keystore.location": "/opt/kafka-monitor/keys/kafka.keystore.jks",
      "consumer.ssl.keystore.password": "changeit"
    }

Regards,
Pradeep

**Comment by andrewchoi5** [comment]
What lines of command are you executing to start the Kafka Monitor from the command line?
Did you run `./gradlew clean build && ./gradlew jar && ./bin/kafka-monitor-start.sh config/kafka-monitor.properties` with the kafka-monitor.properties as outlined in the repo?

**Comment by snmsmanager** [comment]
Hi Andrew,

Yes I did the same. pointed attached config while running kafka-monitor-start.sh . 
Also received below error even ZK and Bootsrap servers are UP and reach .
**java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.**

test-ssl.properties ( change .properties  to .log due to upload issue)
-------------------
[test-ssl.log](https://github.com/linkedin/kafka-monitor/files/4481773/test-ssl.log)

startup log
------------
[sasl_test.log](https://github.com/linkedin/kafka-monitor/files/4481747/sasl_test.log)

Regards,
Pradeep.

**Comment by andrewchoi5** [comment]
```

  ["single-cluster-monitor": {
    "class.name": "com.linkedin.kmf.apps.SingleClusterMonitor",
    "topic": "test",
    "group.id": "test",    
    "zookeeper.connect": "172.26.88.5:2181",
    "bootstrap.servers": "10.48.148.44:9093,10.48.148.45:9093,10.48.148.46:9093,10.48.148.47:9093",
    "request.timeout.ms": 9000,
    "produce.record.delay.ms": 100,
    "topic-management.topicCreationEnabled": false,
    "topic-management.replicationFactor" : 1,
    "topic-management.partitionsToBrokersRatio" : 2.0,
    "topic-management.rebalance.interval.ms" : 600000,
    "topic-management.preferred.leader.election.check.interval.ms" : 300000,
    "topic-management.topicFactory.props": {
    },
    "topic-management.topic.props": {
      "retention.ms": "3600000"
    },
    "produce.producer.props": {
      "client.id": "kmf-client-id",
      "producer.security.protocol": "SASL_PLAINTEXT",
      "sasl.mechanism": "GSSAPI",
      "sasl.kerberos.service.name": "kafka",
      "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"testadmin\" password=\"TestTSG9GVgE@#\";",
      "producer.ssl.truststore.location": "/opt/kafka-monitor/keys/kafka.truststore.jks",
      "producer.ssl.truststore.password": "changeit",
      "producer.ssl.keystore.location": "/opt/kafka-monitor/keys/kafka.keystore.jks",
      "producer.ssl.keystore.password": "changeit"
    },

    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {
      "consumer.security.protocol": "SASL_PLAINTEXT",
      "sasl.mechanism": "GSSAPI",
      "sasl.kerberos.service.name": "kafka",
      "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"testadmin\" password=\"TestTSG9GVgE@#\";",
      "consumer.ssl.truststore.location": "/opt/kafka-monitor/keys/kafka.truststore.jks",
      "consumer.ssl.truststore.password": "changeit",
      "consumer.ssl.keystore.location": "/opt/kafka-monitor/keys/kafka.keystore.jks",
      "consumer.ssl.keystore.password": "changeit"
    }
  },
]
```

For the properties file above attached, if you are using Secure Sockets Layer (SSL) or any non-plaintext security protocol for AdminClient, please configure the following entries in the single-cluster-monitor props, produce.producer.props, **as well as** consume.consumer.props.

https://docs.confluent.io/current/installation/configuration/admin-configs.html

```ssl.key.password
ssl.keystore.location
ssl.keystore.password
ssl.truststore.location
ssl.truststore.password```
