### ISSUE TITLE
Kafka monitor failing due to missing topic with topic creation enabled

### ISSUE THREAD

**Issue by CVTJNII** [linkedin/kafka-monitor#30]
I'm just getting started with kafka-monitor, and my first run is failing with the following exception:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.linkedin.kmf.core.KafkaMonitor.<init>(KafkaMonitor.java:46)
        at com.linkedin.kmf.core.KafkaMonitor.main(KafkaMonitor.java:132)
Caused by: java.lang.RuntimeException: Can not find valid partition number for topic kafka-monitor-topic. Please verify that the topic has been created. Ideally the partition number should be a multiple of number of brokers in the cluster.
        at com.linkedin.kmf.services.ProduceService.<init>(ProduceService.java:75)
        at com.linkedin.kmf.tests.BasicEndToEndTest.<init>(BasicEndToEndTest.java:54)
        ... 6 more
```

This error is technically correct as I have not set up a topic and the target Kafka is a blank dev instance.  However, I'd expect kafka-monitor to start as I have produce.topic.topicCreationEnabled set to true.  For the config I'm running the [example config in the repo](https://github.com/linkedin/kafka-monitor/blob/07c3647277333c5a9fb9b55cffe1716258891e98/config/kafka-monitor.properties) with the zookeeper.connect and bootstrap.servers pointed at my dev Kafka setup.  Rather than die with an exception I'd expect kafka-monitor to set up it's test topic.

**Comment by smccauliff** [comment]
Looking into it.

**Comment by CVTJNII** [comment]
I created the topic and I'm still seeing this error:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[2016-11-08 16:05:14,465] INFO EventThread shut down (org.apache.zookeeper.ClientCnxn)
        at com.linkedin.kmf.core.KafkaMonitor.<init>(KafkaMonitor.java:46)
        at com.linkedin.kmf.core.KafkaMonitor.main(KafkaMonitor.java:132)
Caused by: java.lang.RuntimeException: Can not find valid partition number for topic kafka-monitor-topic. Please verify that the topic has been created. Ideally the partition number should be a multiple of number of brokers in the cluster.
        at com.linkedin.kmf.services.ProduceService.<init>(ProduceService.java:75)
        at com.linkedin.kmf.tests.BasicEndToEndTest.<init>(BasicEndToEndTest.java:54)
        ... 6 more
```

```
kafkat partitions
Topic           Partition       Leader          Replicas                                                ISRs                                                    
kafka-monitor-topic     0               0               [0]                                                     [0]                
```

So perhaps this is something else?  I'm still gathering data myself.

**Comment by CVTJNII** [comment]
I confirmed it is not creating the topic initially, however it's throwing the same error with the topic created, which is a little confusing.

Also, I'm running Confluent Kafka 0.9.0_2.0.0 so I'm running kafka-monitor off the 0.9.0.1 branch, 893c580a3f3267ee9fa753a466bf8207eee093a8

**Comment by CVTJNII** [comment]
AAH this is a PEBCAK issue.  I was passing the wrong ZK path.

**Comment by smccauliff** [comment]
Glad you where able to figure it out.
