### ISSUE TITLE
Error This server does not host this topic-partition

### ISSUE THREAD

**Issue by elizagomes** [linkedin/kafka-monitor#301]
**I have been trying to implement Kafka-monitor on docker but I had the issue below. Could you help me, please?**

-------------
INFO single-cluster-monitor/MultiClusterTopicManagementService started. (com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService)
ERROR single-cluster-monitor/MultiClusterTopicManagementService will stop due to error. (com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService)

java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[kafka-clients-2.3.1.jar:?]
at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) ~[kafka-clients-2.3.1.jar:?]
at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) ~[kafka-clients-2.3.1.jar:?]
at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) ~[kafka-clients-2.3.1.jar:?]
at com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService$TopicManagementHelper.maybeAddPartitions(MultiClusterTopicManagementService.java:298) ~[kafka-monitor-2.3.1.jar:2.3.1]
at com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService$TopicManagementRunnable.run(MultiClusterTopicManagementService.java:179) [kafka-monitor-2.3.1.jar:2.3.1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_202]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_202]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_202]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[2020-07-23 17:09:07,499] INFO single-cluster-monitor/MultiClusterTopicManagementService stopped. (com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService)

Exception in thread "main" java.lang.Exception: Exception occurred while getting the TopicPartitionFuture
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.start(SingleClusterMonitor.java:104)
at com.linkedin.xinfra.monitor.XinfraMonitor.start(XinfraMonitor.java:111)
at com.linkedin.xinfra.monitor.XinfraMonitor.main(XinfraMonitor.java:187)

Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@222a59e6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6c7a164b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]

at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.start(SingleClusterMonitor.java:102)
... 2 more

Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@222a59e6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6c7a164b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]

at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:597)
at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:738)
at com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService.start(MultiClusterTopicManagementService.java:124)
at com.linkedin.xinfra.monitor.services.TopicManagementService.start(TopicManagementService.java:68)
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.lambda$start$0(SingleClusterMonitor.java:96)
at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:717)
at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2010)
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.start(SingleClusterMonitor.java:92)

------

**My xinfra-monitor.properties is setting as follow.**

------
{
  "single-cluster-monitor": {
    "class.name": "com.linkedin.xinfra.monitor.apps.SingleClusterMonitor",
    "topic": "xinfra-monitor-topic",
    "zookeeper.connect": "localhost:2181",
    "bootstrap.servers": "kafka:9092,localhost:9093",
    "request.timeout.ms": 30000,
    "produce.record.delay.ms": 100,
    "topic-management.topicCreationEnabled": false,
    "topic-management.replicationFactor" : 1,
    "topic-management.partitionsToBrokersRatio" : 1.0,
    "topic-management.rebalance.interval.ms" : 600000,
    "topic-management.preferred.leader.election.check.interval.ms" : 300000,
    "topic-management.topicFactory.props": {
    },
    "topic-management.topic.props": {
      "retention.ms": "3600000"
    },
    "produce.producer.props": {
      "client.id": "kmf-client-id",
      "security.protocol": "SSL",
      "ssl.protocol": "TLS", 
      "ssl.truststore.location": "/tmp/certs/truststore.jks",
      "ssl.truststore.password": "fastdata",
      "ssl.keystore.location": "/tmp/certs/kafka.jks",
      "ssl.keystore.password": "fastdata",
      "ssl.key.password": "fastdata"      
    },

    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {
        "security.protocol": "SSL",
        "ssl.protocol": "TLS",
        "ssl.truststore.location": "/tmp/certs/truststore.jks",
        "ssl.truststore.password": "fastdata",
        "ssl.keystore.location": "/tmp/certs/kafka.jks",
        "ssl.keystore.password": "fastdata",
        "ssl.key.password": "fastdata"       
    }
  },
    
  "reporter-service": {
    "class.name": "com.linkedin.xinfra.monitor.services.DefaultMetricsReporterService",
    "report.interval.sec": 1,
    "report.metrics.list": [
      "kmf:type=kafka-monitor:offline-runnable-count",
      "kmf.services:type=produce-service,name=*:produce-availability-avg",
      "kmf.services:type=consume-service,name=*:consume-availability-avg",
      "kmf.services:type=produce-service,name=*:records-produced-total",
      "kmf.services:type=consume-service,name=*:records-consumed-total",
      "kmf.services:type=consume-service,name=*:records-lost-total",
      "kmf.services:type=consume-service,name=*:records-duplicated-total",
      "kmf.services:type=consume-service,name=*:records-delay-ms-avg",
      "kmf.services:type=produce-service,name=*:records-produced-rate",
      "kmf.services:type=produce-service,name=*:produce-error-rate",
      "kmf.services:type=consume-service,name=*:consume-error-rate"
    ]
  },
  
  "jolokia-service": {
    "class.name": "com.linkedin.xinfra.monitor.services.JolokiaService"
  }
}
--------
Thank you!

**Comment by elizagomes** [comment]
This error occurred because I set "topic-management.topicCreationEnabled: false"

**Comment by andrewchoi5** [comment]
Hello elizagomes. Does this problem still persist? Is this issue resolved and if not, have you already had your topic pre-created beforehand, prior to running the Xinfra Monitor App with `"topic-management.topicCreationEnabled: false"`?

**Comment by elizagomes** [comment]
**Hi andrewchoi5. I still have this problem. I am using docker and I have some topics pre-created because it is a ready kafka application that I need to measure performance. I run the Xinfra Monitor before creating topics, but the error persists. I made some changes to my xinfra.properties. See below my properties and the logs. Thank you for your help!**

INFO single-cluster-monitor/MultiClusterTopicManagementService started. (com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService)
ERROR single-cluster-monitor/MultiClusterTopicManagementService will stop due to error. (com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService)
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[kafka-clients-2.3.1.jar:?]
at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) ~[kafka-clients-2.3.1.jar:?]
at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) ~[kafka-clients-2.3.1.jar:?]
at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) ~[kafka-clients-2.3.1.jar:?]
at com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService$TopicManagementHelper.maybeAddPartitions(MultiClusterTopicManagementService.java:298) ~[kafka-monitor-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
at com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService$TopicManagementRunnable.run(MultiClusterTopicManagementService.java:179) [kafka-monitor-2.3.2-SNAPSHOT.jar:2.3.2-SNAPSHOT]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_202]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_202]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_202]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[2020-07-28 12:26:52,909] INFO single-cluster-monitor/MultiClusterTopicManagementService stopped. (com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService)
Exception in thread "main" java.lang.Exception: Exception occurred while getting the TopicPartitionFuture
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.start(SingleClusterMonitor.java:104)
at com.linkedin.xinfra.monitor.XinfraMonitor.start(XinfraMonitor.java:111)
at com.linkedin.xinfra.monitor.XinfraMonitor.main(XinfraMonitor.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3aa078fd rejected from java.util.concurrent.ScheduledThreadPoolExecutor@d23e042[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.start(SingleClusterMonitor.java:102)
	... 2 more
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3aa078fd rejected from java.util.concurrent.ScheduledThreadPoolExecutor@d23e042[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:597)
at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:738)
at com.linkedin.xinfra.monitor.services.MultiClusterTopicManagementService.start(MultiClusterTopicManagementService.java:124)
at com.linkedin.xinfra.monitor.services.TopicManagementService.start(TopicManagementService.java:68)
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.lambda$start$0(SingleClusterMonitor.java:96)
at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:717)
at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2010)
at com.linkedin.xinfra.monitor.apps.SingleClusterMonitor.start(SingleClusterMonitor.java:92)
... 2 more

------------------------------------------

{
  "single-cluster-monitor": {
    "class.name": "com.linkedin.xinfra.monitor.apps.SingleClusterMonitor",
    "topic": "xinfra-monitor-topic",
    "zookeeper.connect": "kafka:2181",
    "bootstrap.servers": "kafka:9092",
    "request.timeout.ms": 30000,
    "produce.record.delay.ms": 100,
    "topic-management.topicCreationEnabled": true,
    "topic-management.replicationFactor" : 1,
    "topic-management.partitionsToBrokersRatio" : 1.0,
    "topic-management.rebalance.interval.ms" : 600000,
    "topic-management.preferred.leader.election.check.interval.ms" : 300000,
    "topic-management.topicFactory.props": {
    },
    "topic-management.topic.props": {
      "retention.ms": "3600000"
    },
    "produce.producer.props": {
      "client.id": "kmf-client-id"      
    },

    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {        
    }
  },
    
  "reporter-service": {
    "class.name": "com.linkedin.xinfra.monitor.services.DefaultMetricsReporterService",
    "report.interval.sec": 1,
    "report.metrics.list": [
      "kmf:type=kafka-monitor:offline-runnable-count",
      "kmf.services:type=produce-service,name=*:produce-availability-avg",
      "kmf.services:type=consume-service,name=*:consume-availability-avg",
      "kmf.services:type=produce-service,name=*:records-produced-total",
      "kmf.services:type=consume-service,name=*:records-consumed-total",
      "kmf.services:type=consume-service,name=*:records-lost-total",
      "kmf.services:type=consume-service,name=*:records-duplicated-total",
      "kmf.services:type=consume-service,name=*:records-delay-ms-avg",
      "kmf.services:type=produce-service,name=*:records-produced-rate",
      "kmf.services:type=produce-service,name=*:produce-error-rate",
      "kmf.services:type=consume-service,name=*:consume-error-rate"
    ]
  },
  
  "jolokia-service": {
    "class.name": "com.linkedin.xinfra.monitor.services.JolokiaService"
  }
}

**Comment by andrewchoi5** [comment]
Hello,

Thanks for your response!

If I understand correctly, you are have some topics pre-created and you're running Xinfra Monitor before creating topics. Xinfra Monitor uses its own internal Xinfra Monitor topic to measure the produce and consume availability of a Kafka cluster. That means XM produces and consumes from an internal, synthetic XM topic in order to determine the performance, and not the other "actual" topics that your application is producing to for your use cases. 

If you have auto topic creation enabled, let's try the following.

Execute the following command.
~/kafka-monitor : `./gradlew clean build && ./gradlew jar && ./bin/xinfra-monitor-start.sh config/xinfra-monitor.properties` 

Configure your properties as follows, but with your zookeeper connect and bootstrap servers correctly hooked up.
```
  "single-cluster-monitor": {
    "class.name": "com.linkedin.xinfra.monitor.apps.SingleClusterMonitor",
    "topic": "xinfra-monitor-topic-new",
    "zookeeper.connect": "localhost:2181",
    "bootstrap.servers": "localhost:9092,localhost:9093",
    "request.timeout.ms": 9000,
    "produce.record.delay.ms": 100,
    "topic-management.topicCreationEnabled": true,
    "topic-management.replicationFactor" : 1,
    "topic-management.partitionsToBrokersRatio" : 2.0,
    "topic-management.rebalance.interval.ms" : 600000,
    "topic-management.preferred.leader.election.check.interval.ms" : 300000,
    "topic-management.topicFactory.props": {
    },
    "topic-management.topic.props": {
      "retention.ms": "3600000"
    },
    "produce.producer.props": {
      "client.id": "kmf-client-id"
    },

    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {
    }
  },

    "offset-commit-service": {
        "class.name": "com.linkedin.xinfra.monitor.services.OffsetCommitService",
        "zookeeper.connect": "localhost:2181",
        "bootstrap.servers": "localhost:9092,localhost:9093",
        "consumer.props": {
            "group.id": "target-consumer-group"
        }
    },

  "jolokia-service": {
    "class.name": "com.linkedin.xinfra.monitor.services.JolokiaService"
  },

  "reporter-service": {
    "class.name": "com.linkedin.xinfra.monitor.services.DefaultMetricsReporterService",
    "report.interval.sec": 1,
    "report.metrics.list": [
        "kmf:type=kafka-monitor:offline-runnable-count",
        "kmf.services:type=produce-service,name=*:produce-availability-avg",
        "kmf.services:type=consume-service,name=*:consume-availability-avg",
        "kmf.services:type=produce-service,name=*:records-produced-total",
        "kmf.services:type=consume-service,name=*:records-consumed-total",
        "kmf.services:type=produce-service,name=*:records-produced-rate",
        "kmf.services:type=produce-service,name=*:produce-error-rate",
        "kmf.services:type=consume-service,name=*:consume-error-rate",
        "kmf.services:type=consume-service,name=*:records-lost-total",
        "kmf.services:type=consume-service,name=*:records-lost-rate",
        "kmf.services:type=consume-service,name=*:records-duplicated-total",
        "kmf.services:type=consume-service,name=*:records-delay-ms-avg",
        "kmf.services:type=commit-availability-service,name=*:offsets-committed-avg",
        "kmf.services:type=commit-availability-service,name=*:offsets-committed-total",
        "kmf.services:type=commit-availability-service,name=*:failed-commit-offsets-avg",
        "kmf.services:type=commit-availability-service,name=*:failed-commit-offsets-total",
        "kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-avg",
        "kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-max",
        "kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-99th",
        "kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-999th",
        "kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-9999th",
        "kmf.services:type=cluster-topic-manipulation-service,name=*:topic-creation-metadata-propagation-ms-avg",
        "kmf.services:type=cluster-topic-manipulation-service,name=*:topic-creation-metadata-propagation-ms-max",
        "kmf.services:type=cluster-topic-manipulation-service,name=*:topic-deletion-metadata-propagation-ms-avg",
        "kmf.services:type=cluster-topic-manipulation-service,name=*:topic-deletion-metadata-propagation-ms-max",
        "kmf.services:type=offset-commit-service,name=*:offset-commit-availability-avg",
        "kmf.services:type=offset-commit-service,name=*:offset-commit-service-success-rate",
        "kmf.services:type=offset-commit-service,name=*:offset-commit-service-success-total",
        "kmf.services:type=offset-commit-service,name=*:offset-commit-service-failure-rate",
        "kmf.services:type=offset-commit-service,name=*:offset-commit-service-failure-total"
    ]
  },

  "cluster-topic-manipulation-service":{
     "class.name":"com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService",
     "bootstrap.servers":"localhost:9092,localhost:9093"
  },
```

If you do **not ** have auto topic creation config enabled, is there any reason you're not enabling it?

**Comment by elizagomes** [comment]
Hi andrewchoi5. I disabled the auto topic creation because I thought that disabling XM would use my topics to generate performance reports. I enabled the auto topic creation and the XM performed perfectly.

In this case, as you explained, will XM use only its own topic or would it use mine too to performance reports generate?

Would you have other software to tell me to measure Kafka's end-to-end performance using my settings (topics, messages, processing)?

I would like to contribute to the XM project by sharing my configuration files to install XM using Docker, docker-compose, prometheus and grafana. It's possible? If so, how do I do it?

Thank you so much for your help!

**Comment by andrewchoi5** [comment]
Hello Eliza,

Glad to see the XM perform work perfectly!

Yes, as you described, Xinfra Monitor will only use its own internal Xinfra Monitor topic to generate performance reports / metrics rather than the your actual topics.

You are certainly welcome to contribute to the this project by sharing your configuration files using Docker, docker-compose, prometheus, Grafana, and etc. Please ensure you have robust unit testing that has wide coverage, after which one of the Xinfra Monitor reviewers will take a look at it and leave a feedback or stamp approval on the PR. 

Thanks!
