### ISSUE TITLE
Batch expiration logged at DEBUG level

### ISSUE THREAD

**Issue by CVTJNII** [linkedin/kafka-monitor#31]
When a message batch expires it's currently logged at the DEBUG level, and is not shown at the default INFO loglevel.  I think this message should probably be WARN level at least as it shows the producer is failing to send messages.

```
[2016-11-08 19:34:31,787] DEBUG end-to-end failed to send message (com.linkedin.kmf.services.ProduceService)
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Batch Expired
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(FutureRecordMetadata.java:56)
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:43)
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:25)
        at com.linkedin.kmf.producer.NewProducer.send(NewProducer.java:35)
        at com.linkedin.kmf.services.ProduceService$ProduceRunnable.run(ProduceService.java:221)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.TimeoutException: Batch Expired
```

**Comment by lindong28** [comment]
Yeah we should change this to WARN.

**Comment by lindong28** [comment]
Changed to WARN level.
