### ISSUE TITLE
Startup fails with Missing required configuration "topic" which has no default value

### ISSUE THREAD

**Issue by guilhemmarchand** [linkedin/kafka-monitor#311]
Hi,

**Using the default properties configuration file:**

`config/xinfra-monitor.properties`

**The startup fails wit the following exception:**

```
[2020-09-07 15:58:51,693] INFO DefaultMetricsReporterServiceConfig values:
	report.interval.sec = 1
	report.metrics.list = [kmf:type=kafka-monitor:offline-runnable-count, kmf.services:type=produce-service,name=*:produce-availability-avg, kmf.services:type=consume-service,name=*:consume-availability-avg, kmf.services:type=produce-service,name=*:records-produced-total, kmf.services:type=consume-service,name=*:records-consumed-total, kmf.services:type=produce-service,name=*:records-produced-rate, kmf.services:type=produce-service,name=*:produce-error-rate, kmf.services:type=consume-service,name=*:consume-error-rate, kmf.services:type=consume-service,name=*:records-lost-total, kmf.services:type=consume-service,name=*:records-lost-rate, kmf.services:type=consume-service,name=*:records-duplicated-total, kmf.services:type=consume-service,name=*:records-delay-ms-avg, kmf.services:type=commit-availability-service,name=*:offsets-committed-avg, kmf.services:type=commit-availability-service,name=*:offsets-committed-total, kmf.services:type=commit-availability-service,name=*:failed-commit-offsets-avg, kmf.services:type=commit-availability-service,name=*:failed-commit-offsets-total, kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-avg, kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-max, kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-99th, kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-999th, kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-9999th, kmf.services:type=cluster-topic-manipulation-service,name=*:topic-creation-metadata-propagation-ms-avg, kmf.services:type=cluster-topic-manipulation-service,name=*:topic-creation-metadata-propagation-ms-max, kmf.services:type=cluster-topic-manipulation-service,name=*:topic-deletion-metadata-propagation-ms-avg, kmf.services:type=cluster-topic-manipulation-service,name=*:topic-deletion-metadata-propagation-ms-max, kmf.services:type=offset-commit-service,name=*:offset-commit-availability-avg, kmf.services:type=offset-commit-service,name=*:offset-commit-service-success-rate, kmf.services:type=offset-commit-service,name=*:offset-commit-service-success-total, kmf.services:type=offset-commit-service,name=*:offset-commit-service-failure-rate, kmf.services:type=offset-commit-service,name=*:offset-commit-service-failure-total]
 (com.linkedin.xinfra.monitor.services.configs.DefaultMetricsReporterServiceConfig)
[2020-09-07 15:58:51,707] INFO ClusterTopicManipulationService constructor initiated com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService (com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService)
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "topic" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:476)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:466)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at com.linkedin.xinfra.monitor.services.configs.TopicManagementServiceConfig.<init>(TopicManagementServiceConfig.java:102)
	at com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService.<init>(ClusterTopicManipulationService.java:91)
	at com.linkedin.xinfra.monitor.services.ClusterTopicManipulationServiceFactory.createService(ClusterTopicManipulationServiceFactory.java:48)
	at com.linkedin.xinfra.monitor.XinfraMonitor.<init>(XinfraMonitor.java:82)
	at com.linkedin.xinfra.monitor.XinfraMonitor.main(XinfraMonitor.java:186)

```

I have tried to find a reason in the properties but no luck yet, I was working ok with an earlier of the kafka-monitor but not with this version yet.

Anything I can try ?

Many thanks in advance,

Guilhem

**Comment by tariq452** [comment]
I have the same issues

**Comment by andrewchoi5** [comment]
Hi Guilhem,

Thanks for raising this issue for the repository!
Have you attempted appending the configuration for the topic name under `ClusterTopicManipulationService` property in your `config/xinfra-monitor.properties`?

**Comment by guilhemmarchand** [comment]
Hi @andrewchoi5 

This is happening with the providing configuration in the config/xinfra-monitor.properties from the repo which contains the following:

```
  "cluster-topic-manipulation-service":{
     "class.name":"com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService",
     "zookeeper.connect": "localhost:2181",
     "bootstrap.servers":"localhost:9092,localhost:9093"
  },
```

I will re-check now in case you fixed something in the meantime or I missed something myself, but I did't have this issue earlier and I am using the provided config sample.

Guilhem

**Comment by guilhemmarchand** [comment]
Nope @andrewchoi5  I still get the same.

`Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "topic" which has no default value.`

In my lab, I am running Zookeeper and Kafka as docker containers (as I always did including the kafka-monitor), for the testing purposes I am running the binary on the guest OS directly, and talking to Zookeeper and Kafka via localhost.

So I have for ex:

```
  "cluster-topic-manipulation-service":{
     "class.name":"com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService",
     "zookeeper.connect": "localhost:12181",
     "bootstrap.servers":"localhost:19092,localhost:29092"
  },
```

I am not using anything else that the builtin config of the repo, and the same issue happens if I build kafka-monitor in a container.

Have you tested out recently ? Looks to me that something broke, or the default config provided in the repo do not work anymore.

**Comment by andrewchoi5** [comment]
Hi Guilhem,

I am currently investigating this. Thanks!

**Comment by andrewchoi5** [comment]
I have tested this copy of the repository locally in my dev environment, which is working successfully. 

https://github.com/linkedin/kafka-monitor/pull/314 

` ./gradlew clean && ./gradlew assemble && ./gradlew build  && ./gradlew idea && ./gradlew jar && ./gradlew jar && ./bin/xinfra-monitor-start.sh config/xinfra-monitor.properties `

```
[2020-09-28 15:26:08,623] INFO ==============================================================
kmf:type=kafka-monitor:offline-runnable-count=0.0
kmf.services:name=single-cluster-monitor,type=produce-service:produce-availability-avg=1.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-availability-avg=1.0
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-total=172.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-consumed-total=154.0
kmf.services:name=single-cluster-monitor,type=produce-service:records-produced-rate=2.87245945991082
kmf.services:name=single-cluster-monitor,type=produce-service:produce-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:consume-error-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-total=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-lost-rate=0.0
kmf.services:name=single-cluster-monitor,type=consume-service:records-duplicated-total=0.0
```
```
  "cluster-topic-manipulation-service":{
     "class.name":"com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService",
     "zookeeper.connect": "localhost:2181",
     "bootstrap.servers":"localhost:9092,localhost:9093",
     "topic": "xinfra-monitor-topic"
  },
```
