### ISSUE TITLE
InvalidReplicaAssignmentException: Duplicate replica assignment found

### ISSUE THREAD

**Issue by ppatierno** [linkedin/kafka-monitor#325]
I am running kafka-monitor (on Kubernetes) alongside a Kafka cluster with 3 brokers.
I have set the partitions to broker ratio to 1.0.
I see that kafka-monitor seems to work fine and it creates the xinfra-monitor-topic with 3 partitions:

```shell
Topic: xinfra-monitor-topic     PartitionCount: 3       ReplicationFactor: 1    Configs: retention.ms=3600000,message.format.version=2.6-IV0
        Topic: xinfra-monitor-topic     Partition: 0    Leader: 2       Replicas: 2     Isr: 2
        Topic: xinfra-monitor-topic     Partition: 1    Leader: 1       Replicas: 1     Isr: 1
        Topic: xinfra-monitor-topic     Partition: 2    Leader: 0       Replicas: 0     Isr: 0
```

but in the kafka-monitor log I see this exception more and more times

```shell
[2020-10-28 12:14:04,373] ERROR Exception occurred while retrieving the brokers count:  (com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService)
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidReplicaAssignmentException: Duplicate replica assignment found: Map(2 -> ArrayBuffer(0, 1, 0), 1 -> ArrayBuffer(1, 0, 2), 0 -> ArrayBuffer(0, 2, 0))
    at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[kafka-clients-2.4.0.jar:?]
    at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) ~[kafka-clients-2.4.0.jar:?]
    at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) ~[kafka-clients-2.4.0.jar:?]
    at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) ~[kafka-clients-2.4.0.jar:?]
    at com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService.createDeleteClusterTopic(ClusterTopicManipulationService.java:189) [kafka-monitor-2.5.3-SNAPSHOT.jar:2.5.3-SNAPSHOT]
    at com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService.access$100(ClusterTopicManipulationService.java:55) [kafka-monitor-2.5.3-SNAPSHOT.jar:2.5.3-SNAPSHOT]
    at com.linkedin.xinfra.monitor.services.ClusterTopicManipulationService$ClusterTopicManipulationServiceRunnable.run(ClusterTopicManipulationService.java:141) [kafka-monitor-2.5.3-SNAPSHOT.jar:2.5.3-SNAPSHOT]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_202]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_202]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_202]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: org.apache.kafka.common.errors.InvalidReplicaAssignmentException: Duplicate replica assignment found: Map(2 -> ArrayBuffer(0, 1, 0), 1 -> ArrayBuffer(1, 0, 2), 0 -> ArrayBuffer(0, 2, 0))
```

Then if I scale up the cluster to 5, as far as I understood the topic should be increased to 5 partitions but it doesn't happen.

**Comment by ppatierno** [comment]
Just noticed that the exception is related to a different topic, the one prefixed as `TOPIC_MANIPULATION_SERVICE_TOPIC` that is not created in the cluster due to the exception itself.

Anyway I still see the problem that when I scale up the cluster to 5 nodes, the partitions of `xinfra-monitor-topic` are still 3 and they are not increased.

**Comment by justindesilets** [comment]
:+1:  I am running into the same issue with a 5 broker cluster that has a separate 5 node zookeeper cluster.
