### ISSUE TITLE
ERROR lassNotFoundException: com.linkedin.kmf.apps.SingleClusterMonitor

### ISSUE THREAD

**Issue by kaizengrowth** [linkedin/kafka-monitor#371]
After unpackaging the jar file with gradle, I'm running into the following error when trying to run this command:

```
$  bin/xinfra-monitor-start.sh config/xinfra-monitor.properties
```

// === ERROR ===
Exception in thread "main" java.lang.ClassNotFoundException: com.linkedin.kmf.apps.SingleClusterMonitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.linkedin.xinfra.monitor.XinfraMonitor.<init>(XinfraMonitor.java:74)
	at com.linkedin.xinfra.monitor.XinfraMonitor.main(XinfraMonitor.java:186)
// ======

**Comment by LincolnTx** [comment]
> After unpackaging the jar file with gradle, I'm running into the following error when trying to run this command:
> 
> ```
> $  bin/xinfra-monitor-start.sh config/xinfra-monitor.properties
> ```
> 
> // === ERROR ===
> 
> Exception in thread "main" java.lang.ClassNotFoundException: com.linkedin.kmf.apps.SingleClusterMonitor at java.net.URLClassLoader.findClass(URLClassLoader.java:387) at java.lang.ClassLoader.loadClass(ClassLoader.java:418) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) at java.lang.ClassLoader.loadClass(ClassLoader.java:351) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:264) at com.linkedin.xinfra.monitor.XinfraMonitor.(XinfraMonitor.java:74) at com.linkedin.xinfra.monitor.XinfraMonitor.main(XinfraMonitor.java:186)
> 
> // ======
> 
> Note: I am not using IntelliJ, but running this straight from command line after un-gradling.

For what I could understand, the kafka monitor need you to pass a class that implements the KMBaseProducer ou Consumer, and for your error message I can tell that you're passing the default valoue, which is a class that doesn't exist in your project. So I'm guessing that if you passa a existing class it'll be alright
