### ISSUE TITLE
Xinfra monitor fails with ClassCastException

### ISSUE THREAD

**Issue by chromy96** [linkedin/kafka-monitor#384]
Starting xinfra monitor throws the following exception: 
```bash
Exception in thread "main" java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
        at org.apache.kafka.common.config.AbstractConfig.getInt(AbstractConfig.java:173)
        at com.linkedin.xinfra.monitor.services.OffsetCommitService.<init>(OffsetCommitService.java:132)
        at com.linkedin.xinfra.monitor.services.OffsetCommitServiceFactory.createService(OffsetCommitServiceFactory.java:53)
        at com.linkedin.xinfra.monitor.XinfraMonitor.<init>(XinfraMonitor.java:82)
        at com.linkedin.xinfra.monitor.XinfraMonitor.main(XinfraMonitor.java:186)

```
Here's a PR that fixes this: https://github.com/linkedin/kafka-monitor/pull/383

**Comment by mhratson** [comment]
Thank you! addressed in #387 🙇
