### ISSUE TITLE
ClassCastException when running Kafka Monitor

### ISSUE THREAD

**Issue by pederpansen** [linkedin/kafka-monitor#58]
With the latest master, I get the following exception:

    ./bin/single-cluster-monitor.sh --topic kafka-monitor-test --broker-list localhost:9092 --zookeeper localhost:2181
    [2017-03-26 13:35:59,032] INFO ProduceServiceConfig values:
    	bootstrap.servers = localhost:9092
    	produce.partitioner.class = com.linkedin.kmf.partitioner.NewKMPartitioner
    	produce.producer.class = com.linkedin.kmf.producer.NewProducer
    	produce.producer.id = kmf-producer
    	produce.record.delay.ms = 100
    	produce.record.size.byte = 100
    	produce.sync = true
    	produce.thread.num = 5
    	topic = kafka-monitor-test
    	zookeeper.connect = localhost:2181
     (com.linkedin.kmf.services.configs.ProduceServiceConfig)
    Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Class
    	at org.apache.kafka.common.config.AbstractConfig.getClass(AbstractConfig.java:117)
    	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:200)
    	at com.linkedin.kmf.services.ProduceService.<init>(ProduceService.java:84)
    	at com.linkedin.kmf.apps.SingleClusterMonitor.<init>(SingleClusterMonitor.java:57)
    	at com.linkedin.kmf.apps.SingleClusterMonitor.main(SingleClusterMonitor.java:263)

From what I can see, Kafka expects the value for the configuration key `ProduceServiceConfig .PARTITIONER_CLASS_CONFIG`to be of type class, when it actually is of type String. 

Or am I missing something here?

**Update**: The issue seems to be related to 1ebe99c1ca3bf098426effb7c9fd8c8797a7d558, the exception does not occur when using revision b13b43cd370b6839a0cd1dcd1bc4b0dce04d652c.

**Comment by lindong28** [comment]
@pederpansen Sorry, we should have tested this before committing the patch. Thanks for catching and reporting this problem! It is fixed now.
