### ISSUE TITLE
Is there any way to run kafka-producer with Kafka 0.8?

### ISSUE THREAD

**Issue by actuallyKasi** [linkedin/kafka-monitor#8]
We are using kafka 0.8.2 version. I am getting the following error while starting kafka monitor.

:~$ tailf  kafka-monitor/logs/kafka-client.log
[2016-06-06 10:18:02,222] WARN block.on.buffer.full config is deprecated and will be removed soon. Please use max.block.ms (org.apache.kafka.clients.producer.KafkaProducer)
[2016-06-06 10:18:02,764] ERROR Uncaught error in kafka producer I/O thread:  (org.apache.kafka.clients.producer.internals.Sender)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'throttle_time_ms': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:71)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:439)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:265)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:216)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:128)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lindong28** [comment]
@actuallyKasi Sorry for late reply. Just noticed the issues.

Server's version should be higher than client's version if there is protocol change. Unfortunately the Kafka Monitor code is using some thing that only exists in Kafka 0.9. But it shouldn't be too hard to twist existing code to allow that. I can make a branch to allow Kafka Monitor to work with 0.8.2 in 2 weeks.

**Comment by lindong28** [comment]
@actuallyKasi I updated the README to note that only Java 8 is supported at this moment. Thanks again for your notice.

**Comment by lindong28** [comment]
@actuallyKasi I have created the branch 0.8.2.2 to work with Kafka 0.8. Please let me know if it doesn't work for you.
