### ISSUE TITLE
when use proxy go to network run gradlew jar error 

### ISSUE THREAD

**Issue by zqc0512** [linkedin/kafka-monitor#82]
./gradlew jar
Downloading https://services.gradle.org/distributions/gradle-3.2.1-bin.zip

Exception in thread "main" java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
i can down use wget to https://services.gradle.org/distributions/gradle-3.2.1-bin.zip file.

**Comment by ibm4mb** [comment]
I've downloaded the zip and edited the "gradle-wrapper.properties" file, and pointed to the downloaded *.zip archive in the same director. 

On to the next error. 
> Could not resolve net.sourceforge.argparse4j:argparse4j:0.5.0.
  Required by:
      project :
   > Could not resolve net.sourceforge.argparse4j:argparse4j:0.5.0.
      > Could not get resource 'https://repo1.maven.org/maven2/net/sourceforge/argparse4j/argparse4j/0.5.0/argparse4j-0.5.0.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/net/sourceforge/argparse4j/argparse4j/0.5.0/argparse4j-0.5.0.pom'.
            > repo1.maven.org: Name or service not known

**Comment by fantasy512** [comment]
Hello, I have the same problem, how do you solve it?

**Comment by waewoo** [comment]
You can use following proxy parameter to run gradlew : 

>  ./gradlew -Dhttp.proxyHost=<YOUR_PROXY> -Dhttp.proxyPort=<YOUR_PROXY_PORT> -Dhttp.proxyUser=<YOUR_LOGIN_PROXY> -Dhttp.proxyPassword=<YOUR_PASS_PROXY>  -Dhttps.proxyHost=<YOUR_PROXY> -Dhttps.proxyPort=<YOUR_PROXY_PORT> -Dhttps.proxyUser=<YOUR_LOGIN_PROXY> -Dhttps.proxyPassword=<YOUR_PASS_PROXY> jar

**Comment by lindong28** [comment]
@zqc0512 It seems that the issue is with gradle downloading dependant library when it is used with proxy. So the issue seems not specific to Kafka Monitor. Sorry we are not able to debug this issue for as we don't run Kafka Monitor with proxy and we are not able to re-produce this issue. Does @waewoo's solution work for you?

**Comment by gigggle** [comment]
@zqc0512 
I build success by doing this, hope it work for you:

vim ~/.gradle/gradle.properties (touch one if this file does not exist )
systemProp.http.proxyHost=proxy.host
systemProp.http.proxyPort=proxy-port
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost

systemProp.https.proxyHost=proxy-host
systemProp.https.proxyPort=proxy-port
systemProp.https.nonProxyHosts=*.nonproxyrepos.com|localhost

**Comment by ankitpateledu** [comment]
I am facing the same issue

**Comment by ankitpateledu** [comment]
in my case  i was using http://proxy.***.com and it was not working. i removed http:// and only used proxy.****.com and it worked

**Comment by andrewchoi5** [comment]
Hi zqc, it seems as though this issue is outdated. Are you still experiencing this issue? Thanks! 😄
