### ISSUE TITLE
`listener_security_protocol_map` not taken into account

### ISSUE THREAD

**Issue by ct16k** [linkedin/kafka-monitor#88]
Hello,

While trying to test kafka-monitor with one of our clusters, I encountered the following error:
```
[2017-07-31 13:54:23,834] ERROR single-cluster-monitor/MultiClusterTopicManagementService will stop due to error. (com.linkedin.kmf.services.MultiClusterTopicManagementService)
kafka.common.KafkaException: Failed to parse the broker info from zookeeper: {"listener_security_protocol_map":{"INT_PLAINTEXT":"PLAINTEXT","EXT_PLAINTEXT":"PLAINTEXT"},"endpoints":["INT_PLAINTEXT://192.168.133.180:9092","EXT_PLAINTEXT://192.168.130.104:9093"],"j
mx_port":9990,"host":"192.168.133.180","timestamp":"1501251189444","port":9092,"version":4}

[...]

Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.kafka.common.protocol.SecurityProtocol.INT_PLAINTEXT

[...]
```
Testing was done with the current head at the time of writing (312abe0).

**Comment by lindong28** [comment]
@ct16k It seems your broker has registered an unknown protocol in the zookeeper. Thus it may not be a problem due to kafka-monitor.

Can you try to produce and consume from your Kafka cluster using the producer/consumer tool in the Apache Kafka repository and see if it works? If it does work, can you provide the commands and properties file you used to start kafka-monitor?

**Comment by ct16k** [comment]
Hello,

Producing and consuming from kafka seems to work without issues so far. We're using `filebeat` to send data to the cluster and the `rdkafka` PHP extension to read from it. The bundled scripts also work fine:

```json
# bin/kafka-verifiable-producer.sh --broker-list 192.168.133.180:9092,192.168.133.181:9092,192.168.133.182:9092 --topic test_topic --max-messages 10
{"name":"startup_complete"}
{"partition":0,"offset":10,"time_ms":1502120096241,"name":"producer_send_success","topic":"test_topic","value":"0","key":null}
{"partition":0,"offset":11,"time_ms":1502120096256,"name":"producer_send_success","topic":"test_topic","value":"1","key":null}
{"partition":0,"offset":12,"time_ms":1502120096258,"name":"producer_send_success","topic":"test_topic","value":"2","key":null}
{"partition":0,"offset":13,"time_ms":1502120096263,"name":"producer_send_success","topic":"test_topic","value":"3","key":null}
{"partition":0,"offset":14,"time_ms":1502120096265,"name":"producer_send_success","topic":"test_topic","value":"4","key":null}
{"partition":0,"offset":15,"time_ms":1502120096267,"name":"producer_send_success","topic":"test_topic","value":"5","key":null}
{"partition":0,"offset":16,"time_ms":1502120096269,"name":"producer_send_success","topic":"test_topic","value":"6","key":null}
{"partition":0,"offset":17,"time_ms":1502120096270,"name":"producer_send_success","topic":"test_topic","value":"7","key":null}
{"partition":0,"offset":18,"time_ms":1502120096271,"name":"producer_send_success","topic":"test_topic","value":"8","key":null}
{"partition":0,"offset":19,"time_ms":1502120096272,"name":"producer_send_success","topic":"test_topic","value":"9","key":null}
{"name":"shutdown_complete"}
{"avg_throughput":30.120481927710845,"target_throughput":-1,"name":"tool_data","sent":10,"acked":10}
```

```json
# bin/kafka-verifiable-consumer.sh --broker-list 192.168.133.180:9092,192.168.133.181:9092,192.168.133.182:9092 --topic test_topic --group-id 0 --verbose
{"timestamp":1502120085561,"name":"startup_complete"}
{"timestamp":1502120085688,"partitions":[],"name":"partitions_revoked"}
{"timestamp":1502120088717,"partitions":[{"topic":"test_topic","partition":0}],"name":"partitions_assigned"}
{"timestamp":1502120096251,"partition":0,"topic":"test_topic","name":"record_data","value":"0","offset":10,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"1","offset":11,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"2","offset":12,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"3","offset":13,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"4","offset":14,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"5","offset":15,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"6","offset":16,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"7","offset":17,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"8","offset":18,"key":null}
{"timestamp":1502120096253,"partition":0,"topic":"test_topic","name":"record_data","value":"9","offset":19,"key":null}
{"timestamp":1502120096254,"count":10,"partitions":[{"topic":"test_topic","partition":0,"count":10,"minOffset":10,"maxOffset":19}],"name":"records_consumed"}
{"timestamp":1502120096275,"offsets":[{"topic":"test_topic","partition":0,"offset":20}],"success":true,"name":"offsets_committed"}
^C{"timestamp":1502120380633,"name":"shutdown_complete"}
```

kafka-monitor was started with the sample properties file, modified to connect the proper hosts:
```json
# cat config/kafka-monitor.properties
{
  "single-cluster-monitor": {
    "class.name": "com.linkedin.kmf.apps.SingleClusterMonitor",
    "topic": "kafka-monitor-topic",
    "zookeeper.connect": "192.168.133.212:2181,192.168.133.213:2181,192.168.133.214:2181",
    "bootstrap.servers": "192.168.133.180:9092,192.168.133.181:9092,192.168.133.182:9092",
    "produce.record.delay.ms": 100,
    "topic-management.topicCreationEnabled": true,
    "topic-management.replicationFactor" : 3,
    "topic-management.partitionsToBrokersRatio" : 2.0,
    "topic-management.rebalance.interval.ms" : 600000,
    "topic-management.topicFactory.props": {
    },
    "topic-management.topic.props": {
    },
    "produce.producer.props": {
      "client.id": "kmf-client-id"
    },
    "consume.latency.sla.ms": "20000",
    "consume.consumer.props": {
    }
  },
  "reporter-service": {
    "class.name": "com.linkedin.kmf.services.DefaultMetricsReporterService",
    "report.interval.sec": 1,
    "report.metrics.list": [
      "kmf:type=kafka-monitor:offline-runnable-count",
      "kmf.services:type=produce-service,name=*:produce-availability-avg",
      "kmf.services:type=consume-service,name=*:consume-availability-avg",
      "kmf.services:type=produce-service,name=*:records-produced-total",
      "kmf.services:type=consume-service,name=*:records-consumed-total",
      "kmf.services:type=consume-service,name=*:records-lost-total",
      "kmf.services:type=consume-service,name=*:records-duplicated-total",
      "kmf.services:type=consume-service,name=*:records-delay-ms-avg",
      "kmf.services:type=produce-service,name=*:records-produced-rate",
      "kmf.services:type=produce-service,name=*:produce-error-rate",
      "kmf.services:type=consume-service,name=*:consume-error-rate"
    ]
  },
  "jetty-service": {
    "class.name": "com.linkedin.kmf.services.JettyService",
    "jetty.port": 8000
  },
  "jolokia-service": {
    "class.name": "com.linkedin.kmf.services.JolokiaService"
  }
}
```

Complete output of a failed start:
```
# bin/kafka-monitor-start.sh config/kafka-monitor.properties
[2017-08-07 18:44:37,816] INFO MultiClusterTopicManagementServiceConfig values:
        topic = kafka-monitor-topic
        topic-management.rebalance.interval.ms = 600000
 (com.linkedin.kmf.services.configs.MultiClusterTopicManagementServiceConfig)
[2017-08-07 18:44:37,850] INFO TopicManagementServiceConfig values:
        topic = kafka-monitor-topic
        topic-management.minPartitionNum = 1
        topic-management.partitionsToBrokersRatio = 2.0
        topic-management.replicationFactor = 3
        topic-management.topicCreationEnabled = true
        topic-management.topicFactory.class.name = com.linkedin.kmf.topicfactory.DefaultTopicFactory
        zookeeper.connect = 192.168.133.212:2181,192.168.133.213:2181,192.168.133.214:2181
 (com.linkedin.kmf.services.configs.TopicManagementServiceConfig)
[2017-08-07 18:44:37,858] INFO ProduceServiceConfig values:
        bootstrap.servers = 192.168.133.180:9092,192.168.133.181:9092,192.168.133.182:9092
        produce.partitioner.class = class com.linkedin.kmf.partitioner.NewKMPartitioner
        produce.producer.class = com.linkedin.kmf.producer.NewProducer
        produce.producer.id = kmf-producer
        produce.record.delay.ms = 100
        produce.record.size.byte = 100
        produce.sync = true
        produce.thread.num = 5
        topic = kafka-monitor-topic
        zookeeper.connect = 192.168.133.212:2181,192.168.133.213:2181,192.168.133.214:2181
 (com.linkedin.kmf.services.configs.ProduceServiceConfig)
[2017-08-07 18:44:37,927] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-08-07 18:44:37,942] INFO Client environment:zookeeper.version=3.4.8--1, built on 02/06/2016 03:18 GMT (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,942] INFO Client environment:host.name=eos-kmg1-all-prod (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,942] INFO Client environment:java.version=1.8.0_141 (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,942] INFO Client environment:java.vendor=Oracle Corporation (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,942] INFO Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,943] INFO Client environment:java.class.path=:/opt/kafka-monitor/bin/../build/libs/kafka-monitor-1.0.0.jar:/opt/kafka-monitor/bin/../build/dependant-libs/ant-1.7.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/ant-launcher-1.7.1.jar:/opt/kafka-$
onitor/bin/../build/dependant-libs/argparse4j-0.5.0.jar:/opt/kafka-monitor/bin/../build/dependant-libs/asm-3.2.jar:/opt/kafka-monitor/bin/../build/dependant-libs/avro-1.4.0.jar:/opt/kafka-monitor/bin/../build/dependant-libs/bsh-2.0b4.jar:/opt/kafka-monitor/bin/../build/$
ependant-libs/commons-collections-3.2.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/commons-lang-2.5.jar:/opt/kafka-monitor/bin/../build/dependant-libs/graphite-client-1.1.0-RELEASE.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jackson-annotations-2.7.0.jar:$
opt/kafka-monitor/bin/../build/dependant-libs/jackson-core-2.7.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jackson-core-asl-1.4.2.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jackson-databind-2.7.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jackso$
-mapper-asl-1.4.2.jar:/opt/kafka-monitor/bin/../build/dependant-libs/java-statsd-client-3.0.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/javax.servlet-3.0.0.v201112011016.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jcommander-1.27.jar:/opt/kafka-monitor/b$
n/../build/dependant-libs/jetty-6.1.22.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jetty-continuation-8.1.19.v20160209.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jetty-http-8.1.19.v20160209.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jetty-io-8.1.1$
.v20160209.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jetty-server-8.1.19.v20160209.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jetty-util-6.1.22.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jetty-util-8.1.19.v20160209.jar:/opt/kafka-monitor/bin/../$
uild/dependant-libs/jline-0.9.94.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jolokia-core-1.3.3.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jolokia-jvm-1.3.3.jar:/opt/kafka-monitor/bin/../build/dependant-libs/jopt-simple-4.9.jar:/opt/kafka-monitor/bin/../b$
ild/dependant-libs/json-20140107.jar:/opt/kafka-monitor/bin/../build/dependant-libs/json-simple-1.1.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/kafka_2.11-0.10.1.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/kafka-clients-0.10.1.1.jar:/opt/kafka-monitor/$
in/../build/dependant-libs/log4j-1.2.17.jar:/opt/kafka-monitor/bin/../build/dependant-libs/lz4-1.3.0.jar:/opt/kafka-monitor/bin/../build/dependant-libs/metrics-core-2.2.0.jar:/opt/kafka-monitor/bin/../build/dependant-libs/netty-3.2.1.Final.jar:/opt/kafka-monitor/bin/../$
uild/dependant-libs/netty-3.7.0.Final.jar:/opt/kafka-monitor/bin/../build/dependant-libs/oro-2.0.8.jar:/opt/kafka-monitor/bin/../build/dependant-libs/paranamer-2.2.jar:/opt/kafka-monitor/bin/../build/dependant-libs/paranamer-ant-2.2.jar:/opt/kafka-monitor/bin/../build/d$
pendant-libs/paranamer-generator-2.2.jar:/opt/kafka-monitor/bin/../build/dependant-libs/qdox-1.10.1.jar:/opt/kafka-monitor/bin/../build/dependant-libs/scala-library-2.11.8.jar:/opt/kafka-monitor/bin/../build/dependant-libs/scala-parser-combinators_2.11-1.0.4.jar:/opt/ka$
ka-monitor/bin/../build/dependant-libs/servlet-api-2.5-20081211.jar:/opt/kafka-monitor/bin/../build/dependant-libs/slf4j-api-1.7.21.jar:/opt/kafka-monitor/bin/../build/dependant-libs/slf4j-log4j12-1.7.21.jar:/opt/kafka-monitor/bin/../build/dependant-libs/snappy-java-1.1$
2.6.jar:/opt/kafka-monitor/bin/../build/dependant-libs/testng-6.8.8.jar:/opt/kafka-monitor/bin/../build/dependant-libs/velocity-1.6.4.jar:/opt/kafka-monitor/bin/../build/dependant-libs/zkclient-0.9.jar:/opt/kafka-monitor/bin/../build/dependant-libs/zookeeper-3.4.8.jar ($
rg.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,943] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,943] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,943] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,943] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,943] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,944] INFO Client environment:os.version=3.10.0-514.26.2.el7.x86_64 (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,944] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,944] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,944] INFO Client environment:user.dir=/opt/kafka-monitor (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,945] INFO Initiating client connection, connectString=192.168.133.212:2181,192.168.133.213:2181,192.168.133.214:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@32464a14 (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:37,987] INFO Opening socket connection to server 192.168.133.212/192.168.133.212:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2017-08-07 18:44:37,996] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2017-08-07 18:44:38,002] INFO Socket connection established to 192.168.133.212/192.168.133.212:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2017-08-07 18:44:38,018] INFO Session establishment complete on server 192.168.133.212/192.168.133.212:2181, sessionid = 0x15d73ebaef00124, negotiated timeout = 30000 (org.apache.zookeeper.ClientCnxn)
[2017-08-07 18:44:38,022] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2017-08-07 18:44:38,431] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-08-07 18:44:38,437] INFO Session: 0x15d73ebaef00124 closed (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:38,441] INFO EventThread shut down for session: 0x15d73ebaef00124 (org.apache.zookeeper.ClientCnxn)
[2017-08-07 18:44:38,548] INFO single-cluster-monitor/ProduceService is initialized. (com.linkedin.kmf.services.ProduceService)
[2017-08-07 18:44:38,557] INFO ConsumeServiceConfig values:
        bootstrap.servers = 192.168.133.180:9092,192.168.133.181:9092,192.168.133.182:9092
        consume.consumer.class = com.linkedin.kmf.consumer.NewConsumer
        consume.latency.percentile.granularity.ms = 1
        consume.latency.percentile.max.ms = 5000
        consume.latency.sla.ms = 20000
        topic = kafka-monitor-topic
        zookeeper.connect = 192.168.133.212:2181,192.168.133.213:2181,192.168.133.214:2181
 (com.linkedin.kmf.services.configs.ConsumeServiceConfig)
[2017-08-07 18:44:38,668] INFO DefaultMetricsReporterServiceConfig values:
        report.interval.sec = 1
        report.metrics.list = [kmf:type=kafka-monitor:offline-runnable-count, kmf.services:type=produce-service,name=*:produce-availability-avg, kmf.services:type=consume-service,name=*:consume-availability-avg, kmf.services:type=produce-service,name=*:records-produced-t
otal, kmf.services:type=consume-service,name=*:records-consumed-total, kmf.services:type=consume-service,name=*:records-lost-total, kmf.services:type=consume-service,name=*:records-duplicated-total, kmf.services:type=consume-service,name=*:records-delay-ms-avg, kmf.servi
ces:type=produce-service,name=*:records-produced-rate, kmf.services:type=produce-service,name=*:produce-error-rate, kmf.services:type=consume-service,name=*:consume-error-rate]
 (com.linkedin.kmf.services.configs.DefaultMetricsReporterServiceConfig)
[2017-08-07 18:44:38,674] INFO JettyServiceConfig values:
        jetty.port = 8000
 (com.linkedin.kmf.services.configs.JettyServiceConfig)
[2017-08-07 18:44:38,948] INFO single-cluster-monitor/MultiClusterTopicManagementService started. (com.linkedin.kmf.services.MultiClusterTopicManagementService)
[2017-08-07 18:44:38,949] INFO Initiating client connection, connectString=192.168.133.212:2181,192.168.133.213:2181,192.168.133.214:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@3b9f4f9e (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:38,950] INFO single-cluster-monitor/ProduceService started (com.linkedin.kmf.services.ProduceService)
[2017-08-07 18:44:38,951] INFO single-cluster-monitor/ConsumeService started (com.linkedin.kmf.services.ConsumeService)
[2017-08-07 18:44:38,951] INFO single-cluster-monitor/SingleClusterMonitor started (com.linkedin.kmf.apps.SingleClusterMonitor)
[2017-08-07 18:44:38,952] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-08-07 18:44:38,953] INFO Opening socket connection to server 192.168.133.214/192.168.133.214:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2017-08-07 18:44:38,953] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2017-08-07 18:44:38,955] INFO Socket connection established to 192.168.133.214/192.168.133.214:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2017-08-07 18:44:38,956] INFO jetty-8.1.19.v20160209 (org.eclipse.jetty.server.Server)
[2017-08-07 18:44:38,960] INFO Session establishment complete on server 192.168.133.214/192.168.133.214:2181, sessionid = 0x35d73eb7ef6010b, negotiated timeout = 30000 (org.apache.zookeeper.ClientCnxn)
[2017-08-07 18:44:38,961] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2017-08-07 18:44:39,030] INFO Started SelectChannelConnector@0.0.0.0:8000 (org.eclipse.jetty.server.AbstractConnector)
[2017-08-07 18:44:39,030] INFO jetty-service/JettyService started at port 8000 (com.linkedin.kmf.services.JettyService)
I> No access restrictor found, access to any MBean is allowed
[2017-08-07 18:44:39,428] INFO jolokia-service/JolokiaService started at port 8778 (com.linkedin.kmf.services.JettyService)
[2017-08-07 18:44:39,430] INFO reporter-service/DefaultMetricsReporterService started (com.linkedin.kmf.services.DefaultMetricsReporterService)
[2017-08-07 18:44:39,431] INFO KafkaMonitor started (com.linkedin.kmf.KafkaMonitor)
[2017-08-07 18:44:39,575] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-08-07 18:44:39,579] INFO Session: 0x35d73eb7ef6010b closed (org.apache.zookeeper.ZooKeeper)
[2017-08-07 18:44:39,580] ERROR single-cluster-monitor/MultiClusterTopicManagementService will stop due to error. (com.linkedin.kmf.services.MultiClusterTopicManagementService)
kafka.common.KafkaException: Failed to parse the broker info from zookeeper: {"listener_security_protocol_map":{"INT_PLAINTEXT":"PLAINTEXT","EXT_PLAINTEXT":"PLAINTEXT"},"endpoints":["INT_PLAINTEXT://192.168.133.180:9092","EXT_PLAINTEXT://192.168.130.104:9093"],"j
mx_port":9990,"host":"192.168.133.180","timestamp":"1502111018241","port":9092,"version":4}
        at kafka.cluster.Broker$.createBroker(Broker.scala:98)
        at kafka.utils.ZkUtils.getBrokerInfo(ZkUtils.scala:814)
        at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:250)
        at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:250)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at kafka.utils.ZkUtils.getAllBrokersInCluster(ZkUtils.scala:250)
        at com.linkedin.kmf.common.Utils.createMonitoringTopicIfNotExists(Utils.java:92)
        at com.linkedin.kmf.topicfactory.DefaultTopicFactory.createTopicIfNotExist(DefaultTopicFactory.java:26)
        at com.linkedin.kmf.services.MultiClusterTopicManagementService$TopicManagementHelper.maybeCreateTopic(MultiClusterTopicManagementService.java:211)
        at com.linkedin.kmf.services.MultiClusterTopicManagementService$TopicManagementRunnable.run(MultiClusterTopicManagementService.java:143)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.kafka.common.protocol.SecurityProtocol.INT_PLAINTEXT
        at java.lang.Enum.valueOf(Enum.java:238)
        at org.apache.kafka.common.protocol.SecurityProtocol.valueOf(SecurityProtocol.java:28)
        at org.apache.kafka.common.protocol.SecurityProtocol.forName(SecurityProtocol.java:89)
        at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:49)
        at kafka.cluster.Broker$$anonfun$1.apply(Broker.scala:87)
        at kafka.cluster.Broker$$anonfun$1.apply(Broker.scala:86)
        at scala.collection.immutable.List.map(List.scala:273)
        at kafka.cluster.Broker$.createBroker(Broker.scala:86)
        ... 21 more
[2017-08-07 18:44:39,584] INFO single-cluster-monitor/MultiClusterTopicManagementService stopped. (com.linkedin.kmf.services.MultiClusterTopicManagementService)
[2017-08-07 18:44:39,585] INFO single-cluster-monitor/MultiClusterTopicManagementService shutdown completed (com.linkedin.kmf.services.MultiClusterTopicManagementService)
[2017-08-07 18:44:39,581] INFO EventThread shut down for session: 0x35d73eb7ef6010b (org.apache.zookeeper.ClientCnxn)
```

**Comment by lindong28** [comment]
@ct16k I see. Thanks for providing the detailed information. It looks like your broker is running Kafka 0.10.2.1 or higher which supports a newer version of broker Info format in zookeeper. Kafka Monitor was not working correctly because it was compiled with Kafka 0.10.1.1, which doesn't recognize that format.

I have bumped up the dependency of kafka from 0.10.1.1 to 0.10.2.1 in the master branch of Kafka Monitor. Can you try the latest version and see if the problem is addressed?

**Comment by ct16k** [comment]
We're testing with a 0.11.0.0 cluster, I forgot to mention. Updating the dependency to 0.10.2 indeed fixed this.

Thank you and keep up the great work!
